//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCertification
    {
        public int UserId { get; set; }
        public int CertificationId { get; set; }
        public System.DateTime CertificationDate { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual User User { get; set; }
    }
}
